FROM ruby:<%= RUBY_VERSION %>

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  libvips \
  nodejs \
  npm \
  git \
  curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

RUN gem install bundler

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bin/docker-entrypoint"]